/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Nat;
export const TicketId = IDL.Nat;
export const Ticket = IDL.Record({ 'id' : TicketId, 'owner' : UserId });

export const idlService = IDL.Service({
  'buyTicket' : IDL.Func([UserId], [TicketId], []),
  'getAllTicketsByUser' : IDL.Func([UserId], [IDL.Vec(Ticket)], ['query']),
  'getTicket' : IDL.Func([TicketId], [Ticket], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Nat;
  const TicketId = IDL.Nat;
  const Ticket = IDL.Record({ 'id' : TicketId, 'owner' : UserId });
  
  return IDL.Service({
    'buyTicket' : IDL.Func([UserId], [TicketId], []),
    'getAllTicketsByUser' : IDL.Func([UserId], [IDL.Vec(Ticket)], ['query']),
    'getTicket' : IDL.Func([TicketId], [Ticket], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };